ant_user_user_users:
    path: /users/
    defaults: { _controller: ApiSocialBundle:User:users }

ant_user_user_users.page:
    path: /users/{page}
    defaults: { _controller: ApiSocialBundle:User:users }
    requirements:
      page: \d+

ant_user_user_show:
    path: /users/{username}-{user_id}
    defaults: { _controller: ApiSocialBundle:User:show }
    requirements:
       username: "[a-zA-Z0-9\-_`^{}\[\]\\~|]+"
       user_id: \d+

ant_user_user_show_by_name:
    path: /users/{username}
    defaults: { _controller: ApiSocialBundle:User:show }
    requirements:
       username: "[a-zA-Z0-9\-_`^{}\[\]\\~|]+"

ant_user_user_photos_show:
    path: /users/{id}/photos
    defaults: { _controller: ApiSocialBundle:User:photos }

ant_user_user_message:
    path: /users/{id}/message
    defaults: { _controller: ApiSocialBundle:User:message }

ant_user_user_messages:
    path: /messages
    defaults: { _controller: ApiSocialBundle:User:messages }

ant_user_user_photos_show.page:
    path: /users/{id}/photos/pages/{page}
    defaults: { _controller: ApiSocialBundle:User:photos }

ant_user_user_photo_show:
    path: /users/{idUser}/photos/{id}
    defaults: { _controller: ApiSocialBundle:User:showPhoto }

ant_chat_chat_show:
    pattern: /webchat/
    defaults: { _controller: ApiSocialBundle:Chat:show }

user_channel_list:
    pattern: /users/{userId}/channels/{list}
    defaults: { _controller: ApiSocialBundle:User:channels }

user_channel_list_paged:
    pattern: /users/{userId}/channels/{list}/{page}
    defaults: { _controller: ApiSocialBundle:User:channels }

channel_show:
    path: /rooms/{slug}
    defaults: { _controller: ApiSocialBundle:Channel:show }

channel_list:
    path:  /rooms/list/
    defaults: { _controller: ApiSocialBundle:Channel:channels}

channel_become_fan:
    path: /rooms/{slug}/become-fan
    defaults: { _controller: ApiSocialBundle:Channel:becomeFan }

channel_list_page:
    path:  /rooms/page/{page}
    defaults: { _controller: ApiSocialBundle:Channel:channels }
    requirements:
        page: \d+

user_profile_photo:
    path:  /users/{username}/profile/photo/{size}
    defaults:  { _controller: ApiSocialBundle:UserProfile:getUserProfilePhoto, size: full }
    requirements:
        size:  full|large|medium|small|icon
