ant_user_user_users:
    path: /usuarios/
    defaults: { _controller: ApiSocialBundle:User:users }

ant_user_user_users.page:
    path: /usuarios/{page}
    defaults: { _controller: ApiSocialBundle:User:users }
    requirements:
      page: \d+

ant_user_user_show:
    path: /usuarios/{username}-{user_id}
    defaults: { _controller: ApiSocialBundle:User:show }
    requirements:
       username: "[a-zA-Z0-9\-_`^{}\[\]\\~|]+"
       user_id: \d+

ant_user_user_show_all_visits:
    path: /usuarios/{username}-{user_id}/visitas
    defaults: { _controller: ApiSocialBundle:UserProfile:showAllVisits }
    requirements:
       username: "[a-zA-Z0-9\-_`^{}\[\]\\~|]+"
       user_id: \d+

ant_user_user_show_by_name:
    path: /usuarios/{username}
    defaults: { _controller: ApiSocialBundle:User:show }
    requirements:
       username: "[a-zA-Z0-9\-_`^{}\[\]\\~|]+"

ant_user_user_photos_show:
    path: /usuarios/{id}/fotos
    defaults: { _controller: ApiSocialBundle:Photo:photos }

ant_user_user_photos_show.page:
    path: /usuarios/{id}/fotos/paginas/{page}
    defaults: { _controller: ApiSocialBundle:Photo:photos }

ant_user_user_photo_show:
    path: /usuarios/{idUser}/fotos/{id}
    defaults: { _controller: ApiSocialBundle:Photo:showPhoto }

ant_user_user_photo_report:
    path: /usuarios/{idUser}/fotos/{id}/reportar
    defaults: { _controller: ApiSocialBundle:Photo:reportPhoto }

ant_user_user_photo_remove:
    path: /usuarios/{idUser}/fotos/{id}/eliminar
    defaults: { _controller: ApiSocialBundle:Photo:removePhoto }

ant_user_user_message:
    path: /usuarios/{id}/mensaje
    defaults: { _controller: ApiSocialBundle:User:message }

ant_user_user_messages:
    path: /mensajes
    defaults: { _controller: ApiSocialBundle:User:messages }

ant_chat_chat_show:
    pattern: /webchat/
    defaults: { _controller: ApiSocialBundle:Chat:show }

user_channel_list:
    pattern: /usuarios/{userId}/canales/{list}
    defaults: { _controller: ApiSocialBundle:User:channels }

user_channel_list_paged:
    pattern: /usuarios/{userId}/canales/{list}/{page}
    defaults: { _controller: ApiSocialBundle:User:channels }

channel_show:
    path: /canales/{slug}
    defaults: { _controller: ApiSocialBundle:Channel:show }

channel_become_fan:
    path: /canales/{slug}/hazte-fan
    defaults: { _controller: ApiSocialBundle:Channel:becomeFan }

channel_remove_fan:
    path: /canales/{slug}/borrar-fan
    defaults: { _controller: ApiSocialBundle:Channel:removeFan }

channel_list:
    path:  /canales/lista/
    defaults: { _controller: ApiSocialBundle:Channel:channels}

channel_list_page:
    path:  /canales/pagina/{page}
    defaults: { _controller: ApiSocialBundle:Channel:channels }
    requirements:
        page: \d+

user_profile_photo:
    path:  /usuarios/{username}/perfil/foto/{size}
    defaults:  { _controller: ApiSocialBundle:UserProfile:getUserProfilePhoto, size: full}
    requirements:
        size:  full|large|medium|small|icon

user_vote:
    path: /votar-foto
    defaults:
        _controller: ApiSocialBundle:Vote:showVote
