parameters:
    users.language: 'es'

services:
  core.twig.channel_photo_url_extension:
    class: Ant\Bundle\ApiSocialBundle\Twig\Extension\ChannelPhotoUrlExtension
    tags:
      - { name: twig.extension }

  core.twig.photo_url_extension:
    class: Ant\Bundle\ApiSocialBundle\Twig\Extension\PhotoUrlExtension
    tags:
      - { name: twig.extension }

  symfony.component.filesystem:
    class: Symfony\Component\Filesystem\Filesystem

  ant_api_social.util.photo_profile:
    class: Ant\Bundle\ApiSocialBundle\Util\PhotoProfileDefault
    arguments: [ @filesystem, %ant.api_social.images_dir% ]

  ant_api_social.file_locator:
    class: Symfony\Component\Config\FileLocator
    arguments: [ %ant_api_social.parameters_service_dir%]

  ant_api_social.services.parameters_service:
     class: Ant\Bundle\ApiSocialBundle\Services\ParametersService
     arguments: [ @ant_api_social.file_locator,  %ant_api_social.parameters_service_file%, %kernel.environment% ]