services:
  core.twig.user_profile_photo_url_extension:
          class: Ant\Bundle\ApiSocialBundle\Twig\Extension\UserProfilePhotoUrlExtension
          tags:
              - { name: twig.extension }
